name: Comment Trigger
on:
  pull_request_review_comment:
    types: [created]

jobs:
  run-script:
    if: contains(github.event.comment.body, '@amp')
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Install the project
        run: uv sync --all-extras --dev
        
      - name: Run test.py
        run: uv run python test.py
