name: Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  run-script:
    if: contains(github.event.comment.body, '@amp') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR branch
        id: pr
        run: |
          PR_NUMBER=$(echo ${{ github.event.issue.number }})
          BRANCH=$(gh pr view $PR_NUMBER --json headRefName -q .headRefName)
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR branch
        run: git checkout ${{ steps.pr.outputs.branch }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run test.py
        run: uv run python test.py
