name: Amp Bot
on:
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  amp:
    if: contains(github.event.comment.body, '@amp')
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      COMMENT_BODY: ${{ github.event.comment.body }}
      AMP_API_KEY: ${{ secrets.AMP_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: thread_cache.json
          key: thread-${{ env.PR_NUMBER }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Sourcegraph Amp
        run: npm install -g @sourcegraph/amp
      - name: Extract user command
        run: |
          USER_COMMAND=$(echo "$COMMENT_BODY" | sed 's/^@amp\s*//')
          echo "USER_COMMAND=$USER_COMMAND" >> $GITHUB_ENV

      - name: Get or create thread ID
        run: |
          if [ -f thread_cache.json ]; then
            THREAD_ID=$(cat thread_cache.json | jq -r '.thread_id')
            echo "THREAD_ID=$THREAD_ID" >> $GITHUB_ENV
            echo "Using cached thread ID: $THREAD_ID"
          else
            echo "Creating new thread"
            THREAD_ID=$(amp threads new | grep -o 'thread-[a-z0-9-]*')
            echo "THREAD_ID=$THREAD_ID" >> $GITHUB_ENV
            echo "{\"thread_id\": \"$THREAD_ID\"}" > thread_cache.json
          fi

      - name: Run Amp with user command
        run: echo "$USER_COMMAND" | amp threads continue "$THREAD_ID"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if ! git diff --quiet || ! git diff --cached --quiet; then
            git add -A
            git commit -m "Changes made by @amp: $USER_COMMAND"
            git fetch origin ${{ github.event.pull_request.head.ref }}
            git rebase origin/${{ github.event.pull_request.head.ref }}
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          fi

      - uses: actions/cache/save@v3
        with:
          path: thread_cache.json
          key: thread-${{ env.PR_NUMBER }}
